### Listar todos os livros
GET http://localhost:8080/livros

### Criar um novo livro
POST http://localhost:8080/livros
Content-Type: application/json

{
  "titulo": "O Senhor dos Anéis",
  "autor": "J.R.R. Tolkien",
  "isbn": "123456"
}

### Atualizar um livro (troque o 1 pelo ID real)
PUT http://localhost:8080/livros/1
Content-Type: application/json

{
  "titulo": "O Senhor dos Anéis - As Duas Torres",
  "autor": "Tolkien",
  "isbn": "123456"
}